apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: simple-app
  name: simple-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: simple-app
  template:
    metadata:
      labels:
        run: simple-app
    spec:
      containers:
      - image: ${IMAGE}
        imagePullPolicy: IfNotPresent
        name: tomcat
        ports:
        - containerPort: 8080
          protocol: TCP
